// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: CourseTopic.proto

package Course

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for CourseTopicService service

func NewCourseTopicServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for CourseTopicService service

type CourseTopicService interface {
	GetTopic(ctx context.Context, in *TopicRequest, opts ...client.CallOption) (*TopicResponse, error)
}

type courseTopicService struct {
	c    client.Client
	name string
}

func NewCourseTopicService(name string, c client.Client) CourseTopicService {
	return &courseTopicService{
		c:    c,
		name: name,
	}
}

func (c *courseTopicService) GetTopic(ctx context.Context, in *TopicRequest, opts ...client.CallOption) (*TopicResponse, error) {
	req := c.c.NewRequest(c.name, "CourseTopicService.GetTopic", in)
	out := new(TopicResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CourseTopicService service

type CourseTopicServiceHandler interface {
	GetTopic(context.Context, *TopicRequest, *TopicResponse) error
}

func RegisterCourseTopicServiceHandler(s server.Server, hdlr CourseTopicServiceHandler, opts ...server.HandlerOption) error {
	type courseTopicService interface {
		GetTopic(ctx context.Context, in *TopicRequest, out *TopicResponse) error
	}
	type CourseTopicService struct {
		courseTopicService
	}
	h := &courseTopicServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&CourseTopicService{h}, opts...))
}

type courseTopicServiceHandler struct {
	CourseTopicServiceHandler
}

func (h *courseTopicServiceHandler) GetTopic(ctx context.Context, in *TopicRequest, out *TopicResponse) error {
	return h.CourseTopicServiceHandler.GetTopic(ctx, in, out)
}
